# Generated by Django 3.1.6 on 2021-07-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20210716_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subimage',
            options={},
        ),
    ]
