# Generated by Django 3.1.6 on 2021-07-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210708_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_image',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
